=== ExaDev-io/breadboard/packages/schema/breadboard.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/breadboard-ai/breadboard/@google-labs/breadboard-schema@1.3.0/packages/schema/breadboard.schema.json",
  "title": "Breadboard",
  "description": "An executable program graph",
  "$defs": {
    "edgePort": {
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[a-zA-Z_][a-zA-Z0-9_-]*$"
        },
        {
          "type": "string",
          "const": "$error",
          "description": "Special port that is used to pass errors"
        }
      ]
    },
    "nodeId": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_-]*$"
    },
    "nodeType": {
      "anyOf": [
        {
          "type": "string",
          "const": "input",
          "description": "A node that represents an input"
        },
        {
          "type": "string",
          "const": "output",
          "description": "A node that represents an output"
        },
        {
          "type": "string",
          "const": "lambda",
          "description": "A node that represents a lambda"
        },
        {
          "pattern": "^[a-zA-Z_][a-zA-Z0-9_-]*$",
          "description": "A custom node type"
        }
      ]
    },
    "nullish": {
      "oneOf": [
        {
          "type": "string",
          "const": ""
        },
        {
          "type": null,
          "const": null
        }
      ]
    }
  },
  "type": "object",
  "required": [
    "nodes",
    "edges"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri-reference"
    },
    "title": {
      "description": "A human-readable title for the graph",
      "type": "string"
    },
    "description": {
      "description": "Description of the graph",
      "type": "string"
    },
    "version": {
      "description": "Semantic version of the graph\nSee https://semver.org/",
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
    },
    "nodes": {
      "description": "All of the nodes in the graph",
      "type": "array",
      "items": {
        "description": "A \"step\" or \"function\" in the program which performs computation",
        "type": "object",
        "required": [
          "id",
          "type"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "description": "Identifier for this node that is unique to this graph",
            "$ref": "#/$defs/nodeId"
          },
          "type": {
            "description": "The type of the node",
            "type": "string",
            "pattern": "^[a-zA-Z_][a-zA-Z0-9_-]*$",
            "$ref": "#/$defs/nodeType"
          },
          "configuration": {
            "description": "Type-specific configuration of the node",
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "edges": {
      "description": "All of the edges in the graph",
      "type": "array",
      "items": {
        "description": "A connection between two nodes through which data flows",
        "type": "object",
        "required": [
          "from",
          "to"
        ],
        "additionalProperties": false,
        "properties": {
          "from": {
            "description": "The ID of the source node",
            "$ref": "#/$defs/nodeId"
          },
          "to": {
            "description": "The ID of the destination node",
            "$ref": "#/$defs/nodeId"
          },
          "out": {
            "description": "The output port of the `from` node.\nIf \"*\", then all outputs of the `from` node are passed to the `to` node. In this case `in` must be empty string or undefined.\nIf undefined or empty string, then no data is passed, and the nodes are instead connected purely for yielding control flow. In this case `in` must be empty string or undefined."
          },
          "in": {
            "description": "The input port of the `to` node.\nMust be empty string or undefined if and only if `out` is either \"*\" or itself empty string or undefined."
          },
          "optional": {
            "description": "If true, nodes connected to this edge won't wait for data to appear before proceding with execution.",
            "type": "boolean"
          },
          "constant": {
            "description": "If true, the most recent data that passed through this edge will remain available indefinitely, instead of being destructively consumed.",
            "type": "boolean"
          }
        },
        "oneOf": [
          {
            "required": [],
            "properties": {
              "out": {
                "$ref": "#/$defs/nullish",
                "description": "If undefined or empty string, then no data is passed, and the nodes are instead connected purely for yielding control flow."
              },
              "in": {
                "$ref": "#/$defs/nullish",
                "description": "Must be empty string or undefined if and only if `out` is either \"*\" or itself empty string or undefined."
              }
            }
          },
          {
            "required": [
              "out"
            ],
            "properties": {
              "out": {
                "const": "*",
                "description": "If \"*\", then all outputs of the `from` node are passed to the `to` node."
              },
              "in": {
                "$ref": "#/$defs/nullish",
                "description": "Must be empty string or undefined if and only if `out` is either \"*\" or itself empty string or undefined."
              }
            }
          },
          {
            "required": [
              "out",
              "in"
            ],
            "properties": {
              "out": {
                "$ref": "#/$defs/edgePort",
                "description": "The output port of the `from` node."
              },
              "in": {
                "$ref": "#/$defs/edgePort",
                "description": "The input port of the `to` node."
              }
            }
          }
        ]
      }
    },
    "kits": {
      "description": "All of the kits this graph depends on",
      "type": "array",
      "items": {
        "description": "A library that will be imported prior to execution for providing handlers for non built-in node types.",
        "type": "object",
        "required": [
          "url"
        ],
        "additionalProperties": false,
        "properties": {
          "url": {
            "description": "Address of the kit",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "graphs": {
      "description": "Sub-graphs that can be referred to by nodes in the parent graph.",
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z_][a-zA-Z0-9_-]*$": {
          "$ref": "#"
        }
      }
    },
    "args": {
      "description": "Arguments that are passed to the graph, useful to bind values to lambdas.",
      "type": "object",
      "additionalProperties": true
    }
  }
}

=== ExaDev-io/breadboard/packages/breadboard-web/public/graphs/translation-RU-ENG.json
{
  "title": "Translation",
  "description": "Translation from Russian to English using the Hugging Face Interface API",
  "version": "0.0.1",
  "edges": [
    {
      "from": "fetch-5",
      "to": "main",
      "out": "*",
      "in": ""
    },
    {
      "from": "fn-3",
      "to": "fetch-5",
      "out": "auth",
      "in": "headers"
    },
    {
      "from": "fn-4",
      "to": "fetch-5",
      "out": "payload",
      "in": "body"
    },
    {
      "from": "main",
      "to": "output-2",
      "out": "output",
      "in": "output"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "apiKey",
      "in": "key"
    },
    {
      "from": "query",
      "to": "fn-4",
      "out": "input",
      "in": "inputs"
    },
    {
      "from": "query",
      "to": "fn-4",
      "out": "use_cache",
      "in": "use_cache"
    },
    {
      "from": "query",
      "to": "fn-4",
      "out": "wait_for_model",
      "in": "wait_for_model"
    }
  ],
  "nodes": [
    {
      "id": "query",
      "type": "input",
      "configuration": {
        "schema": {
          "title": "Hugging Face Schema For RUSSIAN TO ENGLISH TRANSLATION",
          "properties": {
            "apiKey": {
              "type": "string",
              "title": "apiKey",
              "default": "myKey",
              "description": "The hugging face api key"
            },
            "inputs": {
              "type": "string",
              "title": "data",
              "default": "Меня зовут Вольфганг и я живу в Берлине",
              "description": "The data to send to the hugging face api Translation API (Russian To English)"
            },
            "use_cache": {
              "type": "boolean",
              "title": "use_cache",
              "default": "true",
              "description": "Boolean. There is a cache layer on the inference API to speedup requests we have already seen. Most models can use those results as is as models are deterministic (meaning the results will be the same anyway). However if you use a non deterministic model, you can set this parameter to prevent the caching mechanism from being used resulting in a real new query"
            },
            "wait_for_model": {
              "type": "boolean",
              "title": "wait_for_model",
              "default": "false",
              "description": " Boolean. If the model is not ready, wait for it instead of receiving 503. It limits the number of requests required to get your inference done. It is advised to only set this flag to true after receiving a 503 error as it will limit hanging in your application to known places"
            }
          }
        },
        "type": "string"
      }
    },
    {
      "id": "main",
      "type": "output",
      "configuration": {}
    },
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "output": {
              "type": "string",
              "title": "output"
            }
          }
        }
      }
    },
    {
      "id": "fetch-5",
      "type": "fetch",
      "configuration": {
        "method": "POST",
        "url": "https://api-inference.huggingface.co/models/Helsinki-NLP/opus-mt-ru-en"
      }
    },
    {
      "id": "fn-3",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_3 = inputs=>{const key=inputs.key;const auth={Authorization:`Bearer ${key}`};return{auth}};",
        "name": "fn_3",
        "raw": true
      }
    },
    {
      "id": "fn-4",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_4 = input=>{const{inputs,use_cache,wait_for_model}=input;const request={inputs,parameters:{options:{use_cache,wait_for_model}}};const payload=JSON.stringify(request);return{payload}};",
        "name": "fn_4",
        "raw": true
      }
    }
  ]
}

=== ExaDev-io/breadboard/packages/breadboard-web/public/graphs/lm-studio.json
{
  "title": "Lm Studio Proxy",
  "description": "A board that can make requests to a local deployment of LM studio",
  "version": "0.0.1",
  "edges": [
    {
      "from": "fetch-4",
      "to": "main",
      "out": "*",
      "in": ""
    },
    {
      "from": "fn-3",
      "to": "fetch-4",
      "out": "payload",
      "in": "body"
    },
    {
      "from": "main",
      "to": "output-2",
      "out": "output",
      "in": "output"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "max_tokens",
      "in": "max_tokens"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "stream",
      "in": "steam"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "systemContext",
      "in": "systemContext"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "systemRole",
      "in": "systemRole"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "temperature",
      "in": "temperature"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "userContext",
      "in": "userContext"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "userRole",
      "in": "userRole"
    }
  ],
  "nodes": [
    {
      "id": "query",
      "type": "input",
      "configuration": {
        "schema": {
          "title": "LM Studio Schema for https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF",
          "properties": {
            "maxToken": {
              "type": "number",
              "title": "max token",
              "description": "",
              "default": "1.0"
            },
            "stream": {
              "type": "boolean",
              "title": "stream",
              "description": "Boolean to indicate if the model should stream the answer as it is being constructed",
              "default": "false"
            },
            "systemContext": {
              "type": "string",
              "title": "system context",
              "description": "context of the system",
              "default": "default"
            },
            "systemRole": {
              "type": "string",
              "title": "system role",
              "description": "role of the system",
              "default": "system"
            },
            "temperature": {
              "type": "number",
              "title": "temperature",
              "description": "The temperature of the sampling operation. 1 means regular sampling, 0 means always take the highest score, 100.0 is getting closer to uniform probability",
              "default": "1.0"
            },
            "userContext": {
              "type": "string",
              "title": "user context",
              "description": "context of the user",
              "default": "default"
            },
            "userRole": {
              "type": "string",
              "title": "user context",
              "description": "role of the user",
              "default": "user"
            }
          }
        },
        "type": "string"
      }
    },
    {
      "id": "main",
      "type": "output",
      "configuration": {}
    },
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "output": {
              "type": "string",
              "title": "output"
            }
          }
        }
      }
    },
    {
      "id": "fetch-4",
      "type": "fetch",
      "configuration": {
        "headers": {
          "content-type": "application/json"
        },
        "method": "POST",
        "url": "http://host.docker.internal:1234/v1/chat/completions"
      }
    },
    {
      "id": "fn-3",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_3 = input=>{const{systemRole,userRole,systemContext,userContext,temperature,max_tokens,stream}=input;const context1={role:systemRole,content:systemContext};const context2={role:userRole,content:userContext};const payload={messages:[context1,context2],temperature,max_tokens,stream};console.log(\"payload\",payload);return{payload}};",
        "name": "fn_3",
        "raw": true
      }
    }
  ]
}

=== ExaDev-io/breadboard/packages/breadboard-web/public/graphs/firebase_story_from_id.json
{
  "title": "Hacker News Firebase API Story by ID",
  "description": "Board which returns story json",
  "version": "0.0.1",
  "edges": [
    {
      "from": "main",
      "to": "output-2",
      "out": "output",
      "in": "output"
    },
    {
      "from": "spreadResponse",
      "to": "main",
      "out": "*",
      "in": ""
    },
    {
      "from": "fetch",
      "to": "spreadResponse",
      "out": "response",
      "in": "object"
    },
    {
      "from": "urlTemplate",
      "to": "fetch",
      "out": "url",
      "in": "url"
    },
    {
      "from": "storyid",
      "to": "urlTemplate",
      "out": "*",
      "in": ""
    }
  ],
  "nodes": [
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "output": {
              "type": "string",
              "title": "output"
            }
          }
        }
      }
    },
    {
      "id": "main",
      "type": "output",
      "configuration": {}
    },
    {
      "id": "spreadResponse",
      "type": "runJavascript",
      "configuration": {
        "code": "const spreadResponse = inputs=>{const object=inputs.object;if(typeof object!==\"object\"){throw new Error(`object is of type ${typeof object} not object`)}return{...object}};",
        "name": "spreadResponse",
        "raw": true
      }
    },
    {
      "id": "fetch",
      "type": "fetch",
      "configuration": {
        "method": "GET"
      }
    },
    {
      "id": "urlTemplate",
      "type": "urlTemplate",
      "configuration": {
        "template": "https://hacker-news.firebaseio.com/v0/item/{storyid}.json"
      }
    },
    {
      "id": "storyid",
      "type": "input",
      "configuration": {
        "schema": {
          "title": "Hacker News Story id",
          "properties": {
            "storyid": {
              "type": "number",
              "title": "Story ID",
              "default": "39788322",
              "description": "HackerNews Story ID to extract"
            }
          },
          "type": "number"
        }
      }
    }
  ],
  "graphs": {},
  "$schema": "https://raw.githubusercontent.com/breadboard-ai/breadboard/main/packages/schema/breadboard.schema.json"
}

=== ExaDev-io/breadboard/packages/breadboard-web/public/graphs/ollama.json
{
  "title": "Ollama Proxy",
  "description": "Board which interacts with local Ollama server",
  "version": "0.0.1",
  "edges": [
    {
      "from": "fetch-4",
      "to": "main",
      "out": "*",
      "in": ""
    },
    {
      "from": "fn-3",
      "to": "fetch-4",
      "out": "payload",
      "in": "body"
    },
    {
      "from": "main",
      "to": "output-2",
      "out": "output",
      "in": "output"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "model",
      "in": "model"
    },
    {
      "from": "query",
      "to": "fn-3",
      "out": "prompt",
      "in": "prompt"
    }
  ],
  "nodes": [
    {
      "id": "query",
      "type": "input",
      "configuration": {
        "schema": {
          "title": "Inputs for Ollama3 API call",
          "properties": {
            "model": {
              "type": "string",
              "title": "Ollama Model",
              "description": "The Ollama model to respond to the prompt",
              "default": "llama3"
            },
            "prompt": {
              "type": "string",
              "title": "Prompt",
              "description": "Prompt to ask Ollama Model",
              "default": "What are the continents called?"
            }
          }
        },
        "type": "string"
      }
    },
    {
      "id": "main",
      "type": "output",
      "configuration": {}
    },
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "output": {
              "type": "string",
              "title": "output"
            }
          }
        }
      }
    },
    {
      "id": "fetch-4",
      "type": "fetch",
      "configuration": {
        "headers": {
          "content-type": "application/json"
        },
        "method": "POST",
        "url": "http://host.docker.internal:11434/api/generate"
      }
    },
    {
      "id": "fn-3",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_3 = input=>{const payload=input;console.log(\"payload\",payload);return{payload}};",
        "name": "fn_3",
        "raw": true,
        "stream": false
      }
    }
  ]
}

=== ExaDev-io/breadboard/packages/breadboard-web/public/graphs/simplied-hacker-news-algolia-search.json
{
  "title": "Simplified Hacker News Angolia search ",
  "description": "Board which returns API results based on a query using the Hacker News Angolia API",
  "version": "0.0.1",
  "edges": [
    {
      "from": "fetch",
      "to": "spreadResponse",
      "out": "response",
      "in": "object"
    },
    {
      "from": "fn-3",
      "to": "fn-4",
      "out": "output",
      "in": "list"
    },
    {
      "from": "fn-4",
      "to": "output-2",
      "out": "output",
      "in": "output"
    },
    {
      "from": "query",
      "to": "urlTemplate",
      "out": "query",
      "in": "query"
    },
    {
      "from": "query",
      "to": "urlTemplate",
      "out": "tags",
      "in": "tags"
    },
    {
      "from": "spreadResponse",
      "to": "fn-3",
      "out": "hits",
      "in": "list"
    },
    {
      "from": "urlTemplate",
      "to": "fetch",
      "out": "url",
      "in": "url"
    },
    {
      "from": "urlTemplate",
      "to": "output-2",
      "out": "url",
      "in": "url"
    }
  ],
  "nodes": [
    {
      "id": "query",
      "type": "input",
      "configuration": {
        "schema": {
          "title": "Algolia Limit",
          "properties": {
            "limit": {
              "type": "number",
              "title": "limit",
              "description": "The limit",
              "default": "1"
            },
            "query": {
              "type": "string",
              "title": "query",
              "description": "The query",
              "default": "JavaScript"
            },
            "tags": {
              "type": "string",
              "title": "tags",
              "description": "The tags",
              "default": "JavaScript"
            }
          }
        },
        "type": "string"
      }
    },
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "output": {
              "type": "string",
              "title": "output"
            },
            "url": {
              "type": "string",
              "title": "url",
              "description": "The resulting URL that was produced by filling in the placeholders in the template"
            }
          }
        }
      }
    },
    {
      "id": "fetch",
      "type": "fetch",
      "configuration": {
        "method": "GET"
      }
    },
    {
      "id": "fn-3",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_3 = ({list})=>{list.forEach(item=>{delete item[\"children\"];delete item[\"_highlightResult\"];delete item[\"_tags\"];delete item[\"points\"];delete item[\"num_comments\"];delete item[\"objectID\"];delete item[\"updated_at\"]});return{output:list}};",
        "name": "fn_3",
        "raw": true
      }
    },
    {
      "id": "fn-4",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_4 = ({list,limit})=>{return{output:list.slice(0,limit)}};",
        "limit": 10,
        "name": "fn_4",
        "raw": true
      }
    },
    {
      "id": "spreadResponse",
      "type": "runJavascript",
      "configuration": {
        "code": "const spreadResponse = inputs=>{const object=inputs.object;if(typeof object!==\"object\"){throw new Error(`object is of type ${typeof object} not object`)}return{...object}};",
        "name": "spreadResponse",
        "raw": true
      }
    },
    {
      "id": "urlTemplate",
      "type": "urlTemplate",
      "configuration": {
        "page": 1,
        "template": "https://hn.algolia.com/api/v1/search?query={query}&tags={tags}&page={page}"
      }
    }
  ]
}

=== ExaDev-io/breadboard/packages/breadboard-web/public/graphs/wrapped-test.json
{
  "title": "WRAPPED TEST",
  "description": "Board which returns API results based on a query using the Hacker News Angolia API",
  "version": "0.0.1",
  "edges": [
    {
      "from": "fn-3",
      "to": "output-2",
      "out": "output",
      "in": "output"
    }
  ],
  "nodes": [
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "output": {
              "type": "string",
              "title": "output"
            }
          }
        }
      }
    },
    {
      "id": "fn-3",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_3 = async inputs=>{const{graph}=inputs;const runner=await BoardRunner.fromGraphDescriptor(graph);for await(const stop of runner.run()){if(stop.type===\"input\"){stop.inputs={query:\"Docker\",tags:\"story\"}}else if(stop.type===\"output\"){return{output:stop.outputs}}}};",
        "description": "Board which returns API results based on a query using the Hacker News Angolia API",
        "edges": [
          {
            "from": "urlTemplate",
            "to": "fetch",
            "out": "url",
            "in": "url"
          },
          {
            "from": "urlTemplate",
            "to": "output-2",
            "out": "url",
            "in": "url"
          },
          {
            "from": "fn-4",
            "to": "output-2",
            "out": "output",
            "in": "output"
          },
          {
            "from": "query",
            "to": "urlTemplate",
            "out": "query",
            "in": "query"
          },
          {
            "from": "query",
            "to": "urlTemplate",
            "out": "tags",
            "in": "tags"
          },
          {
            "from": "fetch",
            "to": "spreadResponse",
            "out": "response",
            "in": "object"
          },
          {
            "from": "fn-3",
            "to": "fn-4",
            "out": "output",
            "in": "list"
          },
          {
            "from": "spreadResponse",
            "to": "fn-3",
            "out": "hits",
            "in": "list"
          }
        ],
        "graphs": {},
        "name": "fn_3",
        "nodes": [
          {
            "id": "output-2",
            "type": "output",
            "configuration": {
              "schema": {
                "type": "object",
                "properties": {
                  "url": {
                    "type": "string",
                    "title": "url",
                    "description": "The resulting URL that was produced by filling in the placeholders in the template"
                  },
                  "output": {
                    "type": "string",
                    "title": "output"
                  }
                }
              }
            }
          },
          {
            "id": "urlTemplate",
            "type": "urlTemplate",
            "configuration": {
              "template": "https://hn.algolia.com/api/v1/search?query={query}&tags={tags}&page={page}",
              "page": 1
            }
          },
          {
            "id": "fn-4",
            "type": "runJavascript",
            "configuration": {
              "limit": 10,
              "code": "const fn_4 = ({list,limit})=>{return{output:list.slice(0,limit)}};",
              "name": "fn_4",
              "raw": true
            }
          },
          {
            "id": "query",
            "type": "input",
            "configuration": {
              "schema": {
                "title": "Algolia Limit",
                "properties": {
                  "query": {
                    "type": "string",
                    "title": "query",
                    "default": "JavaScript",
                    "description": "The query"
                  },
                  "limit": {
                    "type": "number",
                    "title": "limit",
                    "default": "1",
                    "description": "The limit"
                  },
                  "tags": {
                    "type": "string",
                    "title": "tags",
                    "default": "JavaScript",
                    "description": "The tags"
                  }
                }
              },
              "type": "string"
            }
          },
          {
            "id": "fetch",
            "type": "fetch",
            "configuration": {
              "method": "GET"
            }
          },
          {
            "id": "fn-3",
            "type": "runJavascript",
            "configuration": {
              "code": "const fn_3 = ({list})=>{list.forEach(item=>{delete item[\"children\"];delete item[\"_highlightResult\"];delete item[\"_tags\"];delete item[\"points\"];delete item[\"num_comments\"];delete item[\"objectID\"];delete item[\"updated_at\"]});return{output:list}};",
              "name": "fn_3",
              "raw": true
            }
          },
          {
            "id": "spreadResponse",
            "type": "runJavascript",
            "configuration": {
              "code": "const spreadResponse = inputs=>{const object=inputs.object;if(typeof object!==\"object\"){throw new Error(`object is of type ${typeof object} not object`)}return{...object}};",
              "name": "spreadResponse",
              "raw": true
            }
          }
        ],
        "raw": true,
        "title": "Simplified Hacker News Angolia search ",
        "version": "0.0.1"
      }
    }
  ]
}
